services:
  mysql:
    image: mysql:8.0
    container_name: timetable-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "schedule"
      # Giúp tương thích tốt hơn với driver JDBC và tránh một số vấn đề charset mặc định
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 12

  redis:
    image: redis:7
    container_name: timetable-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12



volumes:
  mysql_data:
  redis_data:

